install_fish() {
  if command -v fish >/dev/null 2>&1; then
    log_info "fish already installed."
    return 0
  fi

  log_info "fish not found. Installing..."

  case "${OS_ID}" in
    linux)
      if command -v apt-get >/dev/null 2>&1; then
        run_as_root apt-get update
        run_as_root apt-get install -y fish
      elif command -v dnf >/dev/null 2>&1; then
        run_as_root dnf install -y fish
      elif command -v yum >/dev/null 2>&1; then
        run_as_root yum install -y fish
      elif command -v pacman >/dev/null 2>&1; then
        run_as_root pacman -Sy --needed --noconfirm fish
      else
        log_warn "Unsupported Linux package manager. Please install fish manually."
        return 1
      fi
      ;;

    macos)
      if command -v brew >/dev/null 2>&1; then
        brew install fish
      else
        log_warn "Homebrew not found. Please install fish manually."
        return 1
      fi
      ;;

    windows)
      if command -v pacman >/dev/null 2>&1; then
        pacman -Sy --needed --noconfirm fish
      else
        log_warn "Automatic fish installation on Windows requires MSYS2 pacman."
        return 1
      fi
      ;;
  esac
}

generate_fish_nvim_path_config() {
  local confd
  local snippet
  local managed_snippet

  confd="${FISH_CONFIG}/conf.d"
  snippet="${confd}/00-nvim-path.fish"
  managed_snippet="${confd}/00-managed-nvim-path.fish"

  mkdir -p "${confd}"

  if [ -f "${managed_snippet}" ] && grep -q "Generated by the Neovim init script" "${managed_snippet}"; then
    rm -f "${managed_snippet}"
  fi

  cat > "${snippet}" <<EOF
# Generated by the Neovim init script.
set -l nvim_bin_dir "${NVIM_BIN_DIR}"

if test -d "\$nvim_bin_dir"
    fish_add_path --path --move "\$nvim_bin_dir"
end
EOF

  log_info "Generated fish Neovim PATH config: ${snippet}"
}
